## Setting up the environment

We need to install

* Miniconda
* Python 3.12
* NumPy, Pandas and Scikit-Learn
* Matplotlib and Seaborn
* Jupyter notebooks

### Install Miniconda

```bash
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
```

Initialize conda for your shell
```bash
conda init bash
```

Restart shell
```bash
source ~/.bashrc
```

### Create the conda environment

In your terminal, run this command to create the environment
```bash
conda create -n ml-practice python=3.12
```

Activate the environment
```bash
conda activate ml-practice
```

Installing libraries
```bash
conda install numpy pandas scikit-learn seaborn matplotlib jupyterlab -y
```

You can now launch Jupyter Lab
```bash
jupyter lab
```

In [1]:
import pandas as pd
pd.__version__

'2.3.1'

### Getting the data
Read Car Fuel Efficiency dataset with pandas

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [5]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

## Q2. Records count

How many records are in the dataset?

In [10]:
df.shape[0]

9704

## Q3. Fuel types

How many fuel types are presented in the dataset?

In [12]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [13]:
df['fuel_type'].nunique()

2

## Q4. Missing values

How many columns in the dataset have missing values?

In [16]:
missing_columns = df.isnull().sum()

In [21]:
(missing_columns > 0).sum()

np.int64(4)

In [25]:
len(missing_columns[missing_columns > 0])

4

## Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [30]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

23.759122836520497

## Q6. Median value of horsepower

1. Find the median value of the `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use the `fillna` method to fill the missing values in the `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.

Has it changed?

In [32]:
median_before = df["horsepower"].median()

In [33]:
median_before

149.0

In [40]:
mode_value = df["horsepower"].mode()[0]

In [41]:
mode_value

np.float64(152.0)

In [42]:
df["horsepower"] = df["horsepower"].fillna(mode_value)

In [44]:
median_after = df["horsepower"].median()

In [45]:
median_after

152.0

In [46]:
median_after > median_before

True

## Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

In [2]:
import numpy as np

In [4]:
asia_cars = df[df['origin'] == 'Asia']

In [5]:
asia_cars

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [6]:
asia_cars = asia_cars[['vehicle_weight', 'model_year']]

In [7]:
asia_cars

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [8]:
asia_cars_first_7 = asia_cars.head(7)

In [9]:
asia_cars_first_7

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [10]:
X = asia_cars_first_7.values

In [11]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [12]:
XTX = X.T.dot(X)

In [13]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [14]:
XTX_inv = np.linalg.inv(XTX)

In [15]:
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [16]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [17]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [18]:
w = XTX_inv.dot(X.T).dot(y)

In [19]:
w

array([0.01386421, 0.5049067 ])

In [20]:
w.sum()

np.float64(0.5187709081074016)